[project]
name = "fiscal-query"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "chromadb>=1.5.9",
    "ipykernel>=7.3.0",
    "langchain-text-splitters>=1.1.2",
    "openai>=3.13.0",
    "pandas>=3.0.5",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "tiktoken>=0.14.0",
    "tqdm>=4.70.1",
]
